CREATE TABLE CLIENTE (
ID_CLIENTE INT PRIMARY KEY,
CPF VARCHAR(14) NOT NULL,
NOME VARCHAR(100) NOT NULL,
RG VARCHAR(14),
DATA_EXPEDICAO DATE,
ORGAO_EXPEDICAO VARCHAR(10),
UF VARCHAR(2),
DATA_NASCIMENTO DATE NOT NULL,
SEXO VARCHAR(1) NOT NULL,
ESTADO_CIVIL VARCHAR(20) NOT NULL
);

CREATE TABLE ENDERECO_CLIENTE (
ID_ENDCLI INT PRIMARY KEY,
ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID_CLIENTE),
CEP VARCHAR(10) NOT NULL,
LOGRADOURO VARCHAR(255) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
COMPLEMENTO VARCHAR(20),
BAIRRO VARCHAR(100)NOT NULL,
CIDADE VARCHAR(100)NOT NULL,
UF VARCHAR(2) NOT NULL
);